name: Security Scan

on:
  push:
  pull_request:

jobs:
  security-scan:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: TruffleHog Secret Scanner
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./


    - name: Bandit Python Security Scan
      run: |
        pip install bandit
        bandit -r backend


    - name: Hadolint Dockerfile Scan
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: backend/Dockerfile

    - name: Build Backend Image
      run: |
        docker build -t secure-backend ./backend


    - name: Build Frontend Image
      run: |
        docker build -t secure-frontend ./frontend


    - name: Trivy Backend Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: secure-backend
        severity: HIGH,CRITICAL


    - name: Trivy Frontend Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: secure-frontend
        severity: HIGH,CRITICAL
