name: Security Scan and Deploy

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Python Tools
        run: |
          python3 -m pip install bandit --break-system-packages


      - name: Bandit Python Security Scan
        run: |
          bandit -r backend || true


      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./


      - name: Hadolint Backend Dockerfile Scan
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile


      - name: Hadolint Frontend Dockerfile Scan
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile


      - name: Build Backend Image
        run: |
          docker build -t secure-backend ./backend


      - name: Build Frontend Image
        run: |
          docker build -t secure-frontend ./frontend


      - name: Trivy Backend Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-backend
          severity: HIGH,CRITICAL
          exit-code: 0


      - name: Trivy Frontend Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-frontend
          severity: HIGH,CRITICAL
          exit-code: 0
